### ISSUE TITLE
AWS: Define Metric Store for Canary

### ISSUE THREAD

**Issue by nparks-kenzan** [kenzanlabs/capstan#32]
Unlike GCP, AWS does not provide a metric store for Canary Analysis. We need to pick what metric integration that would be easy to package for educational purposes.

**Comment by dbathgate** [comment]
What about prometheus? That works for spinnaker right?

**Comment by nparks-kenzan** [comment]
That is probably the one to go with. The question is more about the best way to packages what is ever chosen that is simple without hurdles for people to use it.

**Comment by dbathgate** [comment]
Prometheus is pretty good at not being intrusive in the application tier. 

Implementing at the application means providing a /metrics endpoint that Prometheus can scrape over HTTP.
Prometheus can be added to an application without the need for a Prometheus server because Prometheus works on pull model.

**Comment by nparks-kenzan** [comment]
GCP is stackdriver and AWS will be Prometheus
